### PR TITLE
Update cooperatives.yml - added MetaGame

### PR DESCRIPTION
**Pull request by peth-yursick**

### CODE REVIEW

**Comment by pbrudnick** [comment]
Sorry, your project looks great, but coophub is intended for **cooperatives companies**, are you a cooperative or working as it?

**Comment by pbrudnick** [comment]
Closing it due to no feedback.

**Comment by peth-yursick** [comment]
> Closing it due to no feedback.

oh damn, somehow missed the above question, sorry! 😅
yes, we are a platform cooperative - bootstrapped, built & governed fully by a community

**Comment by pbrudnick** [comment]
Great, feel free to open a new PR!

**Pull request closed without merging**
